language: java

jdk:
  - oraclejdk8

before_install:
  - npm install -g bower

after_success:
  - mvn jacoco:report coveralls:report

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/eee27732e50d40f73bf2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always