language: java

jdk:
  - oraclejdk8

before_install:
  - npm install -g bower

nv:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "NX0Use1toWL55JrlT+VOamXGhG9tKfmkgVSMBH4qSVSVY/Fgvdqpujr7l/3ejIEpEr7rRPEvAG0ZoC7i5kufE+S+5yJFHrqBqbKRFplqXSVv+Bhnh0rvEaLdinsFAx8QoBaY+Kr6BImv5A/bQTEZtGCAeOUk0zOKsN8NzDHYbzM="

after_success:
  - mvn clean test jacoco:report coveralls:report